// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDslyBo07__v2KixwcfxTfv0TSmrsFXpbE',
    appId: '1:489092810579:web:34226fa2453d1e05bb43a6',
    messagingSenderId: '489092810579',
    projectId: 'yourvl',
    authDomain: 'yourvl.firebaseapp.com',
    storageBucket: 'yourvl.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1oLVArlR2DwKyQ73adAyojbWkZ-5itEw',
    appId: '1:489092810579:android:a2b0905e7b6db59abb43a6',
    messagingSenderId: '489092810579',
    projectId: 'yourvl',
    storageBucket: 'yourvl.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd4-b8v92TPQWBQ8XSvspsemAhwKql83c',
    appId: '1:489092810579:ios:255650826557cfbabb43a6',
    messagingSenderId: '489092810579',
    projectId: 'yourvl',
    storageBucket: 'yourvl.appspot.com',
    iosClientId: '489092810579-9i8qqtdog1e9s808udhuk2g5mer7fime.apps.googleusercontent.com',
    iosBundleId: 'com.arcushub.kathanote.kathanote',
  );
}
